import type { Metadata } from 'next';

import { interVar, roboto } from '@/assets/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${interVar.variable} ${roboto.variable} font-sans`}
    >
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
